
[target.aarch64-linux-android]
linker = "/home/thomas/Android/Sdk/ndk/28.0.13004108/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android35-clang"

[target.x86_64-linux-android]
linker = "/home/thomas/Android/Sdk/ndk/28.0.13004108/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android35-clang"
