[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["dylib"]

[dependencies]
stitchy-core = { path = "../../Stitchy/crates/stitchy-core", features = ["parser"] }
jni = { version = "0.21.1", default-features = false }
